// <auto-generated />
using System;
using ConnectaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnectaMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324192613_connecta1625")]
    partial class connecta1625
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConnectaMVC.Models.ConsultaModel", b =>
                {
                    b.Property<string>("ConsultaId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AnotacoesConsulta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DataHoraConsulta")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("DuracaoConsulta")
                        .HasColumnType("time(6)");

                    b.Property<string>("ProntuarioId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ConsultaId");

                    b.HasIndex("ProntuarioId");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("ConnectaMVC.Models.PacienteModel", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HistoricoPaciente")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("ConnectaMVC.Models.ProntuarioModel", b =>
                {
                    b.Property<string>("ProntuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PacienteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PsicologoResponsavelId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Queixas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoProntuario")
                        .HasColumnType("int");

                    b.HasKey("ProntuarioId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("PsicologoResponsavelId");

                    b.ToTable("Prontuario");
                });

            modelBuilder.Entity("ConnectaMVC.Models.PsicologoModel", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TipoPerfil")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Psicologo");
                });

            modelBuilder.Entity("ConnectaMVC.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("ConnectaMVC.Models.UsuarioModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TipoModulo")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ConnectaMVC.Models.ConsultaModel", b =>
                {
                    b.HasOne("ConnectaMVC.Models.ProntuarioModel", "Prontuario")
                        .WithMany("ConsultasVinculadas")
                        .HasForeignKey("ProntuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("ConnectaMVC.Models.PacienteModel", b =>
                {
                    b.HasOne("ConnectaMVC.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConnectaMVC.Models.ProntuarioModel", b =>
                {
                    b.HasOne("ConnectaMVC.Models.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnectaMVC.Models.PsicologoModel", "PsicologoResponsavel")
                        .WithMany()
                        .HasForeignKey("PsicologoResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("PsicologoResponsavel");
                });

            modelBuilder.Entity("ConnectaMVC.Models.PsicologoModel", b =>
                {
                    b.HasOne("ConnectaMVC.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ConnectaMVC.Models.ProntuarioModel", b =>
                {
                    b.Navigation("ConsultasVinculadas");
                });
#pragma warning restore 612, 618
        }
    }
}
